
version: '3.8'

services:
  ridejoy-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    restart: unless-stopped
    # Uncomment for development with hot-reload
    # volumes:
    #   - ./:/app
    #   - /app/node_modules
    # command: npm run dev
